rm(list = ls())
setwd("/Users/vincent/Momocs/")
require(MASS) ; require(rgl)
source("R/global.R")
source("R/Out.R")
source("R/FourierCore.R")
load("data/bot.rda")
load("data/trilo.rda")
load("data/mosquito.rda")
load("data/hearts.rda")
load("~/Dropbox/MG-out.rda")

bot <- coo.sample(bot, 64)
b <- bot[5]
botE <- eFourier(bot, 6, norm=TRUE)
botP <- pca(botE)
ms <- meanshapes(botE, 1)
